language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/juliareleases -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'versioninfo()'
  - julia -e 'Pkg.add("DataFrames")'
  - julia -e 'Pkg.add("TimeData")'
  - julia -e 'Pkg.update()'
#  - julia -e 'Pkg.init(); Pkg.add("WorldBankDataTd")'
  - julia -e 'Pkg.init(); Pkg.clone("https://github.com/JuliaFinMetriX/WorldBankDataTd.jl.git")'
  - echo "Testing latest release:"
  - julia -e 'Pkg.test("WorldBankDataTd")'
  - julia -e 'Pkg.checkout("WorldBankDataTd")'
  - echo "Testing master:"
  - mkdir -p ~/.julia/WorldBankDataTd
  - cp -R ./* ~/.julia/WorldBankDataTd/
  - julia --code-coverage ./test/runtests.jl

after_success:
  - julia -e 'cd(Pkg.dir("WorldBankDataTd")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
